apiVersion: 1

datasources:

  - name: VictoriaMetrics Live
    uid: victoriametrics-live
    type: prometheus
    access: proxy
    url: http://vmauth:8427
    basicAuth: true
    basicAuthUser: grafana_live
    secureJsonData:
      basicAuthPassword: "CHANGE_ME_GRAFANA_LIVE"

  - name: VictoriaMetrics Report
    uid: victoriametrics-report
    type: prometheus
    access: proxy
    url: http://vmauth:8427
    basicAuth: true
    basicAuthUser: grafana_report
    secureJsonData:
      basicAuthPassword: "CHANGE_ME_GRAFANA_REPORT"

  - name: VictoriaLogs
    uid: victorialogs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://vmauth:8427
    basicAuth: true
    basicAuthUser: grafana_logs
    secureJsonData:
      basicAuthPassword: "CHANGE_ME_GRAFANA_LOGS"
    jsonData:
      maxLines: 500
      derivedFields:
        - datasourceUid: tempo # Điền UID của Tempo data source
          matcherRegex: trace_id[":\s]+([a-f0-9]{32})
          name: Trace
          url: $$${__value.raw}

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToProfiles:
        datasourceUid: pyroscope
        tags:
          - key: 'service.name'
            value: 'service_name'

  - name: Pyroscope
    uid: pyroscope
    type: pyroscope
    access: proxy
    url: http://pyroscope:4040
