{
 "title": "Ceph - OSD Repartition",
 "description": "Ceph OSD Repartition",
 "tags": [
  "ceph",
  "osd"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "device_class",
    "query": {
     "query": "label_values(ceph_osd_metadata{cluster=\"$cluster\"}, device_class)"
    }
   },
   {
    "name": "osd",
    "label": "OSD",
    "query": {
     "query": "label_values(ceph_osd_metadata{cluster=\"$cluster\", device_class=\"$device_class\"}, ceph_daemon)"
    }
   },
   { "name": "limit", "query": "60" }
  ]
 },
 "panels": [
  {
   "title": "OSD > $limit %",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc((ceph_osd_stat_bytes_used{cluster=\"$cluster\",ceph_daemon=~\"$osd\"}/ceph_osd_stat_bytes{cluster=\"$cluster\",ceph_daemon=~\"$osd\"}*100)>$limit)",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "OSD > $limit %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(ceph_osd_stat_bytes_used{cluster=\"$cluster\",ceph_daemon=~\"$osd\"}/ceph_osd_stat_bytes{cluster=\"$cluster\",ceph_daemon=~\"$osd\"}*100)>$limit",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "Global Repartition",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "ceph_osd_stat_bytes_used{cluster=\"$cluster\",ceph_daemon=~\"$osd\"}/ceph_osd_stat_bytes{cluster=\"$cluster\",ceph_daemon=~\"$osd\"}",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  { "title": "OSD: $osd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "$osd",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 18 },
   "repeat": "osd",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_osd_stat_bytes_used{cluster=\"$cluster\",ceph_daemon=~\"$osd\"}/ceph_osd_stat_bytes{ceph_daemon=~\"$osd\"}"
    }
   ]
  }
 ]
}