global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:

  - job_name: "node-exporter"

    static_configs:
      - targets:
          - "node-exporter:9100"

        labels:
          environment: "lab"
          host: "monitoring-server"
  - job_name: "test-servers"

    static_configs:

      - targets:
          - "172.31.3.94:9100"
        labels:
          host: "target-server-01"
          environment: "uat"

  - job_name: "victoriametrics"
    static_configs:
      - targets: ["victoriametrics:8428"]

  - job_name: "victorialogs"
    static_configs:
      - targets: ["victorialogs:9428"]

  - job_name: "vmagent"
    static_configs:
      - targets: ["vmagent:8429"]
